services:
  caddy:
    image: caddy:latest
    container_name: caddy_public
    restart: unless-stopped
    cap_add:
    - NET_ADMIN
    ports:
    - "80:80"
    - "443:443"
    - "443:443/udp"
    volumes:
    - /home/ubuntu/caddy/data:/data
    - /home/ubuntu/caddy/config:/config
    - /home/ubuntu/caddy/caddyfile:/etc/caddy