volumes:
  n8n_storage:

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - N8N_HOST=hostnameforn8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://hostnameforn8n/
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_HIDE_USAGE_PAGE=true
      - GENERIC_TIMEZONE=America/Los_Angeles
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./local_files:/files
    network_mode: service:n8n-on-hstgr

  n8n-on-hstgr:
    image: tailscale/tailscale:latest
    hostname: n8n-on-hstgr
    ports:
      - 5678:5678
    environment:
      - TS_AUTHKEY=tailscaleauthkey
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-n8n/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped


    
