defaultProxyProvider: default
docker:
  local:
    host: unix:///var/run/docker.sock
    defaultProxyProvider: default
tailscale:
  providers:
    default: # name of the provider
      authKeyFile: "/run/secrets/tsauthkey"
      controlUrl: https://controlplane.tailscale.com # use this to override the default control URL
http:
  hostname: 0.0.0.0
  port: 8080
log:
  level: info # set logging level info, error or trace  
  json: false # set to true to enable json logging
proxyAccessLog: true # set to true to enable container access log