services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - TZ=America/Los_Angeles
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
