version: '3.7'
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ./config:/config
    restart: unless-stopped
    secrets:
      - tsauthkey

volumes:
  datadir:

secrets:
  tsauthkey:
    file: ~/.config/tsdproxy/tsauthkey